# Generated by Django 2.1 on 2018-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=250)),
                ('opis', models.TextField(blank=True, null=True)),
                ('cena', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('dostepny', 'dostepny'), ('niedostepny', 'niedostepny')], max_length=20)),
                ('is_actual', models.BooleanField()),
            ],
        ),
    ]
