# Generated by Django 2.1 on 2018-08-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nazwa',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cena',
            new_name='price',
        ),
    ]
