# Generated by Django 2.1 on 2018-08-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20180819_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
